問題 1  
x に10は代入されないが、x を宣言したことになり、例外は発生しない。  

```ruby
def foo
  x = 10 if false
    puts x
  end
end
foo
```
